{{- if .Values.keyVaultSecrets.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "task-api.fullname" . }}-spc
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "task-api.fullname" . }}-secrets
      type: Opaque
      data:
        - objectName: task-api-secret-key
          key: task-api-secret-key
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.keyVaultSecrets.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.keyVaultSecrets.vaultName | quote }}
    tenantId: {{ .Values.keyVaultSecrets.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: task-api-secret-key
          objectType: secret
{{- end }}
