apiVersion: v2
name: task-api
description: Task API Helm chart — platform-gitops demo microservice
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: saikiranrko
keywords:
  - fastapi
  - python
  - demo
